"""Known vehicles."""

DATA = {
  "XBA": "KWID CN",
  "XBB": "KWID BR",
  "X06": "TWINGO",
  "X44": "TWINGO II",
  "X07": "TWINGO III",
  "X07Ph2": "TWINGO III Ph2",
  "X77": "MODUS",
  "X35": "SYMBOL/THALIA",
  "X65": "CLIO II",
  "X85": "CLIO III",
  "X98": "CLIO IV",
  "XJA": "CLIO V",
  "X87": "CAPTUR",
  "XJB": "CAPTUR II",
  "XHA": "KAPTUR",
  "XHAPh2": "KAPTUR Ph2",
  "XJE": "CAPTUR II CN",
  "XBC": "CAPTUR II IN",
  "XJC": "ARKANA",
  "X38": "FLUENCE",
  "XFF": "FLUENCE II",
  "X64": "MEGANE/SCENIC I",
  "X84": "MEGANE/SCENIC II",
  "X84Ph2": "MEGANE/SCENIC II Ph2",
  "X95": "MEGANE/SCENIC III",
  "X95Ph2": "MEGANE/SCENIC III Ph2",
  "XFB": "MEGANE IV",
  "XFBPh2": "MEGANE IV Ph2",
  "XFF": "MEGANE IV SEDAN",
  "XFA": "SCENIC IV",
  "XFAPh2": "SCENIC IV Ph2",
  "X56": "LAGUNA",
  "X74": "LAGUNA II",
  "X74Ph2": "LAGUNA II Phase 2",
  "X91": "LAGUNA III",
  "X47": "LAGUNA III (tricorps)",
  "X66": "ESPACE III",
  "X81": "ESPACE IV",
  "XFC": "ESPACE V",
  "XFCPh2": "ESPACE V Ph2",
  "X73": "VELSATIS",
  "X43": "LATITUDE",
  "XFD": "TALISMAN",
  "XFDPh2": "TALISMAN Ph2",
  "H45": "KOLEOS",
  "XZG": "KOLEOS II",
  "XZJ": "KOLEOS II CN",
  "HFE": "KADJAR",
  "HFEPh2": "KADJAR Ph2",
  "XZH": "KADJAR CN",
  "X33": "WIND",
  "X09": "TWIZY",
  "X10": "ZOE",
  "X10Ph2": "ZOE Ph2",
  "X76": "KANGOO I",
  "X61": "KANGOO II",
  "X61Ph2": "KANGOO II Ph2",
  "XFK": "KANGOO III",
  "X24": "MASCOTT",
  "X83": "TRAFFIC II",
  "X82": "TRAFFIC III",
  "X70": "MASTER II",
  "X62": "MASTER III",
  "X62Ph2": "MASTER III Ph2",
  "X90": "LOGAN/SANDERO",
  "X52": "LOGAN/SANDERO II",
  "XJI": "LOGAN/SANDERO III",
  "X79": "DUSTER",
  "X79Ph2": "DUSTER Ph2",
  "XJD": "DUSTER II",
  "X67": "DOKKER",
  "XJK": "Dokker II",
  "X92": "LODGY",
  "X90": "LARGUS",
  "XGA": "XRAY",
  "AS1": "ALPINE",
  "X02E": "MICRA",
  "X21B": "NOTE",
  "X13A": "JUKE" ,
  "X60A": "NAVARRA ALASKAN",
  "XNN": "KICKS",
  "P32": "QASHQAI",
}
